# Generated by Django 2.1.11 on 2020-05-06 19:18

from django.db import migrations, models
import tilesets.models


class Migration(migrations.Migration):

    dependencies = [
        ('tilesets', '0012_auto_20190923_0257'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregationGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('higlassVersion', models.CharField(default='', max_length=16)),
                ('uuid', models.CharField(default=tilesets.models.decoded_slugid, max_length=100, unique=True)),
                ('groups', models.TextField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
