# Generated by Django 2.1.11 on 2020-05-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tilesets', '0013_aggregationgroups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregationgroups',
            name='tilesetUid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
